#!/bin/bash

git remote set-url origin git+ssh://git@github.com/scarbajalv/hello-world.git

git add .

echo "Insert Commit Message: "

read commitmsg

echo $commitmsg

git commit -m "hola que tal"

git push origin master

echo SUCCESS!

#algunas ediciones !!
