#!/bin/bash

./launch-pythia_v08 120 40 1 1 1 > /dev/null &
./launch-pythia_v08 120 40 1 20 2 > /dev/null &
./launch-pythia_v08 120 40 1 40 3 > /dev/null &
./launch-pythia_v08 120 40 1 60 4 > /dev/null &
./launch-pythia_v08 120 40 1 80 5 > /dev/null &
./launch-pythia_v08 120 40 1 100 6

zenity --info \
--text '<span font="32"> Procesos \n completados </span>' \
--width=300 --height=200