#!/bin/bash

# ./X pdgid ebeam maxoffaxis deltaoffaxis seed_i index

# ./multigun ebeam mHNL.dat maxoffaxis deltaoffaxis seed nroot index

k=$1

make multigun$k

# Abrimos el file con los nombres de los "mHNL.dat"
masses="./mathbrs/confignames.dat"

j=$5

while IFS= read -r line1
do
	echo -e "\nUtilizando archivo de configuración ebeam=$2, $line1, maxoffaxis=$3, deltaoffaxis=$4, seed=$j, index=$6..."
	# hacemos el seed = nroot = j
	./multigun$k $2 "./mathbrs/$line1" $3 $4 $j $j $6
	j=$(( j + 1 )) # increase number by 1 
done < "$masses"
